import { Product } from '@/types';

export const categories = [
  { id: 'audio', name: 'Audio Profesional', slug: 'audio', productCount: 345 },
  { id: 'iluminacion', name: 'Iluminación Escénica', slug: 'iluminacion', productCount: 289 },
  { id: 'efectos', name: 'Efectos Especiales', slug: 'efectos', productCount: 156 },
  { id: 'cables', name: 'Cables y Conectores', slug: 'cables', productCount: 210 },
  { id: 'consolas', name: 'Consolas y Mixers', slug: 'consolas', productCount: 98 },
  { id: 'microfonos', name: 'Micrófonos', slug: 'microfonos', productCount: 120 },
  { id: 'parlantes', name: 'Parlantes y Monitores', slug: 'parlantes', productCount: 185 },
];

export const products: Product[] = [
  {
    id: '1',
    name: 'Mixer Digital Behringer X32',
    description: 'Consola digital de 40 entradas, 25 buses, procesador de efectos integrado y control vía iPad.',
    price: 2450000,
    category: 'consolas',
    sku: 'BEH-X32',
    rating: 4.8,
    imageUrl: '/images/products/mixer.jpg',
  },
  {
    id: '2',
    name: 'Parlante Activo JBL EON712',
    description: 'Parlante de 12" 1000W RMS, Bluetooth, DSP integrado y manejo de sonido de alta precisión.',
    price: 1890000,
    category: 'parlantes',
    sku: 'JBL-EON712',
    rating: 4.6,
    imageUrl: '/images/products/parlante.jpg',
  },
  {
    id: '3',
    name: 'Micrófono Shure SM58',
    description: 'Micrófono dinámico vocal, patrón cardioide, construcción robusta para uso en escena.',
    price: 285000,
    category: 'microfonos',
    sku: 'SH-SM58',
    rating: 4.9,
    imageUrl: '/images/products/microfono.jpg',
  },
  {
    id: '4',
    name: 'Cable XLR Canon 5m',
    description: 'Cable balanceado de audio profesional, conector Neutrik, blindaje de cobre y aislamiento de goma.',
    price: 12500,
    category: 'cables',
    sku: 'CAB-XLR5',
    rating: 4.5,
    imageUrl: '/images/products/cable.jpg',
  },
  {
    id: '5',
    name: 'Moving Head LED 150W',
    description: 'Cabezal móvil LED de 150W, zoom motorizado, colores RGBW, control DMX y efectos preprogramados.',
    price: 3200000,
    category: 'iluminacion',
    sku: 'MH-LED150',
    rating: 4.7,
    imageUrl: '/images/products/moving-head.jpg',
  },
  {
    id: '6',
    name: 'Máquina de Humo Low Fog',
    description: 'Generador de humo de bajo nivel para efectos escénicos, control remoto y depósito de 5L.',
    price: 890000,
    category: 'efectos',
    sku: 'FOG-LF100',
    rating: 4.4,
    imageUrl: '/images/products/humo.jpg',
  },
  {
    id: '7',
    name: 'Interface de Audio Focusrite 2i2',
    description: 'Interface USB de 2 entradas/2 salidas, preamps de clase A, conversores de 24-bit/192kHz.',
    price: 420000,
    category: 'audio',
    sku: 'FOC-2I2',
    rating: 4.8,
    imageUrl: '/images/products/interface.jpg',
  },
  {
    id: '8',
    name: 'Monitor de Estudio Yamaha HS8',
    description: 'Monitor de estudio activo de 8", respuesta plana, control de room y alta precisión.',
    price: 1350000,
    category: 'parlantes',
    sku: 'YAM-HS8',
    rating: 4.9,
    imageUrl: '/images/products/monitor.jpg',
  },
  {
    id: '9',
    name: 'Consola de Iluminación DMX512',
    description: 'Consola de control de iluminación 512 canales, 24 submasters, programas de chases y efectos.',
    price: 1850000,
    category: 'iluminacion',
    sku: 'DMX-CON512',
    rating: 4.6,
    imageUrl: '/images/products/consola-dmx.jpg',
  },
  {
    id: '10',
    name: 'Auriculares Sennheiser HD25',
    description: 'Auriculares de monitoreo profesional, diseño over-ear, respuesta de frecuencia 16-22kHz.',
    price: 380000,
    category: 'audio',
    sku: 'SEN-HD25',
    rating: 4.7,
    imageUrl: '/images/products/auriculares.jpg',
  },
];

export const featuredProducts = products.slice(0, 6);